# Site settings
title: Transitland
email: hello@mapzen.com
description: >
  A community-edited data service aggregating transit networks
  across metropolitan and rural areas around the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.transit.land" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - vendor
  - Rakefile
  - Gemfile
  - .*
  - circle.yml
  - README.md
  - config/
  - lib/
  - deploy/
# this is the docs part that are not ready to go out
  - how-it-works/datastore/api-usage-and-authentication.md
  - how-it-works/datastore/feeds.md
  - how-it-works/datastore/stops.md
  - how-it-works/datastore/routes-and-route-stop-pattern.md
